/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodayIndexRouteImport } from './routes/today.index'
import { Route as JourneyIndexRouteImport } from './routes/journey.index'
import { Route as TodayCheckInRouteImport } from './routes/today.check-in'
import { Route as ProfileSetupRouteImport } from './routes/profile.setup'
import { Route as OnboardingStepRouteImport } from './routes/onboarding.$step'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ProfileSetupIndexRouteImport } from './routes/profile.setup.index'
import { Route as ProfileSetupStepRouteImport } from './routes/profile.setup.$step'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayIndexRoute = TodayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TodayRoute,
} as any)
const JourneyIndexRoute = JourneyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JourneyRoute,
} as any)
const TodayCheckInRoute = TodayCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => TodayRoute,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile/setup',
  path: '/profile/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => OnboardingRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileSetupIndexRoute = ProfileSetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileSetupRoute,
} as any)
const ProfileSetupStepRoute = ProfileSetupStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => ProfileSetupRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/journey': typeof JourneyRouteWithChildren
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/today': typeof TodayRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/profile/setup': typeof ProfileSetupRouteWithChildren
  '/today/check-in': typeof TodayCheckInRoute
  '/journey/': typeof JourneyIndexRoute
  '/today/': typeof TodayIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/profile/setup/$step': typeof ProfileSetupStepRoute
  '/profile/setup/': typeof ProfileSetupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/today/check-in': typeof TodayCheckInRoute
  '/journey': typeof JourneyIndexRoute
  '/today': typeof TodayIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/profile/setup/$step': typeof ProfileSetupStepRoute
  '/profile/setup': typeof ProfileSetupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/journey': typeof JourneyRouteWithChildren
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/today': typeof TodayRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/profile/setup': typeof ProfileSetupRouteWithChildren
  '/today/check-in': typeof TodayCheckInRoute
  '/journey/': typeof JourneyIndexRoute
  '/today/': typeof TodayIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/profile/setup/$step': typeof ProfileSetupStepRoute
  '/profile/setup/': typeof ProfileSetupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/journey'
    | '/mcp'
    | '/onboarding'
    | '/today'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/onboarding/$step'
    | '/profile/setup'
    | '/today/check-in'
    | '/journey/'
    | '/today/'
    | '/.mcp/invoke-tool/$tool'
    | '/profile/setup/$step'
    | '/profile/setup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/onboarding'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/onboarding/$step'
    | '/today/check-in'
    | '/journey'
    | '/today'
    | '/.mcp/invoke-tool/$tool'
    | '/profile/setup/$step'
    | '/profile/setup'
  id:
    | '__root__'
    | '/'
    | '/journey'
    | '/mcp'
    | '/onboarding'
    | '/today'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/onboarding/$step'
    | '/profile/setup'
    | '/today/check-in'
    | '/journey/'
    | '/today/'
    | '/.mcp/invoke-tool/$tool'
    | '/profile/setup/$step'
    | '/profile/setup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JourneyRoute: typeof JourneyRouteWithChildren
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  TodayRoute: typeof TodayRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ProfileSetupRoute: typeof ProfileSetupRouteWithChildren
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today/': {
      id: '/today/'
      path: '/'
      fullPath: '/today/'
      preLoaderRoute: typeof TodayIndexRouteImport
      parentRoute: typeof TodayRoute
    }
    '/journey/': {
      id: '/journey/'
      path: '/'
      fullPath: '/journey/'
      preLoaderRoute: typeof JourneyIndexRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/today/check-in': {
      id: '/today/check-in'
      path: '/check-in'
      fullPath: '/today/check-in'
      preLoaderRoute: typeof TodayCheckInRouteImport
      parentRoute: typeof TodayRoute
    }
    '/profile/setup': {
      id: '/profile/setup'
      path: '/profile/setup'
      fullPath: '/profile/setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/setup/': {
      id: '/profile/setup/'
      path: '/'
      fullPath: '/profile/setup/'
      preLoaderRoute: typeof ProfileSetupIndexRouteImport
      parentRoute: typeof ProfileSetupRoute
    }
    '/profile/setup/$step': {
      id: '/profile/setup/$step'
      path: '/$step'
      fullPath: '/profile/setup/$step'
      preLoaderRoute: typeof ProfileSetupStepRouteImport
      parentRoute: typeof ProfileSetupRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JourneyRouteChildren {
  JourneyIndexRoute: typeof JourneyIndexRoute
}

const JourneyRouteChildren: JourneyRouteChildren = {
  JourneyIndexRoute: JourneyIndexRoute,
}

const JourneyRouteWithChildren =
  JourneyRoute._addFileChildren(JourneyRouteChildren)

interface OnboardingRouteChildren {
  OnboardingStepRoute: typeof OnboardingStepRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingStepRoute: OnboardingStepRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface TodayRouteChildren {
  TodayCheckInRoute: typeof TodayCheckInRoute
  TodayIndexRoute: typeof TodayIndexRoute
}

const TodayRouteChildren: TodayRouteChildren = {
  TodayCheckInRoute: TodayCheckInRoute,
  TodayIndexRoute: TodayIndexRoute,
}

const TodayRouteWithChildren = TodayRoute._addFileChildren(TodayRouteChildren)

interface ProfileSetupRouteChildren {
  ProfileSetupStepRoute: typeof ProfileSetupStepRoute
  ProfileSetupIndexRoute: typeof ProfileSetupIndexRoute
}

const ProfileSetupRouteChildren: ProfileSetupRouteChildren = {
  ProfileSetupStepRoute: ProfileSetupStepRoute,
  ProfileSetupIndexRoute: ProfileSetupIndexRoute,
}

const ProfileSetupRouteWithChildren = ProfileSetupRoute._addFileChildren(
  ProfileSetupRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JourneyRoute: JourneyRouteWithChildren,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  TodayRoute: TodayRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ProfileSetupRoute: ProfileSetupRouteWithChildren,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
