/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodayIndexRouteImport } from './routes/today.index'
import { Route as ProfileSetupRouteImport } from './routes/profile.setup'
import { Route as OnboardingStepRouteImport } from './routes/onboarding.$step'
import { Route as ProfileSetupIndexRouteImport } from './routes/profile.setup.index'
import { Route as ProfileSetupStepRouteImport } from './routes/profile.setup.$step'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayIndexRoute = TodayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TodayRoute,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile/setup',
  path: '/profile/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => OnboardingRoute,
} as any)
const ProfileSetupIndexRoute = ProfileSetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileSetupRoute,
} as any)
const ProfileSetupStepRoute = ProfileSetupStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => ProfileSetupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/today': typeof TodayRouteWithChildren
  '/onboarding/$step': typeof OnboardingStepRoute
  '/profile/setup': typeof ProfileSetupRouteWithChildren
  '/today/': typeof TodayIndexRoute
  '/profile/setup/$step': typeof ProfileSetupStepRoute
  '/profile/setup/': typeof ProfileSetupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/$step': typeof OnboardingStepRoute
  '/today': typeof TodayIndexRoute
  '/profile/setup/$step': typeof ProfileSetupStepRoute
  '/profile/setup': typeof ProfileSetupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/today': typeof TodayRouteWithChildren
  '/onboarding/$step': typeof OnboardingStepRoute
  '/profile/setup': typeof ProfileSetupRouteWithChildren
  '/today/': typeof TodayIndexRoute
  '/profile/setup/$step': typeof ProfileSetupStepRoute
  '/profile/setup/': typeof ProfileSetupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/today'
    | '/onboarding/$step'
    | '/profile/setup'
    | '/today/'
    | '/profile/setup/$step'
    | '/profile/setup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/onboarding/$step'
    | '/today'
    | '/profile/setup/$step'
    | '/profile/setup'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/today'
    | '/onboarding/$step'
    | '/profile/setup'
    | '/today/'
    | '/profile/setup/$step'
    | '/profile/setup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  TodayRoute: typeof TodayRouteWithChildren
  ProfileSetupRoute: typeof ProfileSetupRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today/': {
      id: '/today/'
      path: '/'
      fullPath: '/today/'
      preLoaderRoute: typeof TodayIndexRouteImport
      parentRoute: typeof TodayRoute
    }
    '/profile/setup': {
      id: '/profile/setup'
      path: '/profile/setup'
      fullPath: '/profile/setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/profile/setup/': {
      id: '/profile/setup/'
      path: '/'
      fullPath: '/profile/setup/'
      preLoaderRoute: typeof ProfileSetupIndexRouteImport
      parentRoute: typeof ProfileSetupRoute
    }
    '/profile/setup/$step': {
      id: '/profile/setup/$step'
      path: '/$step'
      fullPath: '/profile/setup/$step'
      preLoaderRoute: typeof ProfileSetupStepRouteImport
      parentRoute: typeof ProfileSetupRoute
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingStepRoute: typeof OnboardingStepRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingStepRoute: OnboardingStepRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface TodayRouteChildren {
  TodayIndexRoute: typeof TodayIndexRoute
}

const TodayRouteChildren: TodayRouteChildren = {
  TodayIndexRoute: TodayIndexRoute,
}

const TodayRouteWithChildren = TodayRoute._addFileChildren(TodayRouteChildren)

interface ProfileSetupRouteChildren {
  ProfileSetupStepRoute: typeof ProfileSetupStepRoute
  ProfileSetupIndexRoute: typeof ProfileSetupIndexRoute
}

const ProfileSetupRouteChildren: ProfileSetupRouteChildren = {
  ProfileSetupStepRoute: ProfileSetupStepRoute,
  ProfileSetupIndexRoute: ProfileSetupIndexRoute,
}

const ProfileSetupRouteWithChildren = ProfileSetupRoute._addFileChildren(
  ProfileSetupRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  TodayRoute: TodayRouteWithChildren,
  ProfileSetupRoute: ProfileSetupRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
